In [18]:
import numpy as np
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt


dataset = load_boston()

X = dataset.data
y = dataset.target[:,np.newaxis]

print((X.shape())

def compute_cost(X, y, params):
    n_samples = len(y)
    h = X @ params# multiply theta and X , @:it is an function in numpy to mulitply matrises  
    return (1/(2*n_samples))*np.sum((h-y)**2)


SyntaxError: unexpected EOF while parsing (<ipython-input-18-2069f9e72b85>, line 12)

In [12]:
    n = int(input())
    
    count=0
    while n!=0:
        n = n & (n << 1)
        count+=1
    print(count)

30
4


In [19]:
def gradient_descent(X, y, params, learning_rate, n_iters):
    n_samples = len(y)
    J_history = np.zeros((n_iters,1))

    for i in range(n_iters):
        params = params - (learning_rate/n_samples) * X.T @ (X @ params - y) 
        J_history[i] = compute_cost(X, y, params)

    return (J_history, params)

In [5]:
type(0b10001)

int

In [6]:
0b10001

17

In [22]:
def gradient_descent(X, y, params, learning_rate, n_iters):
    n_samples = len(y)
    J_history = np.zeros((n_iters,1))

    for i in range(n_iters):
        params = params - (learning_rate/n_samples) * X.T @ (X @ params - y) 
        J_history[i] = compute_cost(X, y, params)

    return (J_history, params)


In [20]:
class LinearRegression():
    def __init__(self, X, y, alpha=0.03, n_iter=1500):

        self.alpha = alpha
        self.n_iter = n_iter
        self.n_samples = len(y)
        self.n_features = np.size(X, 1)
        self.X = np.hstack((np.ones(
            (self.n_samples, 1)), (X - np.mean(X, 0)) / np.std(X, 0)))
        self.y = y[:, np.newaxis]
        self.params = np.zeros((self.n_features + 1, 1))
        self.coef_ = None
        self.intercept_ = None

    def fit(self):

        for i in range(self.n_iter):
            self.params = self.params - (self.alpha/self.n_samples) * \
            self.X.T @ (self.X @ self.params - self.y)

        self.intercept_ = self.params[0]
        self.coef_ = self.params[1:]

        return self

    def score(self, X=None, y=None):

        if X is None:
            X = self.X
        else:
            n_samples = np.size(X, 0)
            X = np.hstack((np.ones(
                (n_samples, 1)), (X - np.mean(X, 0)) / np.std(X, 0)))

        if y is None:
            y = self.y
        else:
            y = y[:, np.newaxis]

        y_pred = X @ self.params
        score = 1 - (((y - y_pred)**2).sum() / ((y - y.mean())**2).sum())

        return score

    def predict(self, X):
        n_samples = np.size(X, 0)
        y = np.hstack((np.ones((n_samples, 1)), (X-np.mean(X, 0)) \
                            / np.std(X, 0))) @ self.params
        return y

    def get_params(self):

        return self.params

In [23]:
x=np.array([1,2,3])

In [24]:
x

array([1, 2, 3])

In [25]:
x.T

array([1, 2, 3])

In [26]:
x=np.array([[1,2,3],[4,5,6]])

In [27]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [29]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [30]:
arr.T

array([[-1. ,  4. ,  2.6,  3. ],
       [ 2. , -0.5,  0. , -7. ],
       [ 0. ,  6. ,  7. ,  4. ],
       [ 4. ,  0. ,  8. ,  2. ]])